version: '3.3'

services:

  exmoarbitrage:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TEMPLATE: /app/
      PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
